name: muzero
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=22.2.2
  - cudatoolkit=11.3
  - pytorch
  - numpy=1.19.5
  - cython=0.29.23
  - tensorboard
  - pip:
    - ray==2.0.1
    - gym[atari,roms,accept-rom-license]==0.15.7
    - opencv-python==4.5.1.48
    - kornia==0.6.6
